### ISSUE TITLE
请更新到最新版本

### ISSUE THREAD

**Issue by money150604** [fmricky/Getui-NoIDFA#1]
RT

**Comment by fmricky** [comment]
已更新

**Comment by cherishloveyou** [comment]
pods需要更新到1.6.2版本，因为前面版本含有JSPatch审核被拒绝

**Comment by fmricky** [comment]
已更新 @cherishloveyou 
也欢迎直接PR给我提交更新
pod 'GetuiSDK-NoIDFA', '~> 1.6.2.0'
